[Pass] FuseTIR
Hzfengsy/relax pull request #14
Opened 2022-03-31 14:35 UTC by jinhongyii

This pass relies on RegenerateDef which hasn't been merged, so the changed files will contain its relevant files. Please skip them when reviewing.

Tuple-related tests rely on https://github.com/tlc-pack/relax/pull/116. After it is merged, I will update the tests.

2022-03-31 14:35 UTC, jinhongyii commented
cc: @MasterJH5574 @Hzfengsy @tqchen

2022-03-31 15:07 UTC, Hzfengsy commented on src/relax/transform/fuse_tir.cc
> +      in_subfunction_ = true;
I guess `primitive_func` may be a better name

2022-03-31 15:07 UTC, Hzfengsy commented on src/relax/transform/fuse_tir.cc
> +      const Array<Expr> call_tir_args = Downcast<Tuple>(call->args[1])->fields;
```suggestion
      const Array<Expr>& call_tir_args = Downcast<Tuple>(call->args[1])->fields;
```

2022-04-01 13:21 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +class Inliner : public ExprMutator {
inline is a very generic name, consider a more specific name FuseTIRInliner

2022-04-01 13:21 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +class Inliner : public ExprMutator {
inline is a very generic name, consider a more specific name FuseTIRInliner

2022-04-01 13:21 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +  Optional<Function> get_relax_call(const VarBindingNode* binding) {
CamelCase

2022-04-01 13:21 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +  Optional<Function> get_relax_call(const VarBindingNode* binding) {
CamelCase

2022-04-01 13:22 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +        tir::PrimFunc func = opt_f.value();
Logic flow: FusePrimFunc into a separate sub function

2022-04-01 13:22 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +        tir::PrimFunc func = opt_f.value();
Logic flow: FusePrimFunc into a separate sub function

2022-04-01 13:23 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +  void VisitBinding_(const VarBindingNode* binding) final {
Likely you can and should overload `VisitExpr_(const CallNode*)` instead

2022-04-01 13:25 UTC, jinhongyii commented on src/relax/transform/fuse_tir.cc
> +  void VisitBinding_(const VarBindingNode* binding) final {
I have already overloaded VisitExpr_(const CallNode*)

2022-04-01 13:26 UTC, tqchen requested changes

2022-04-01 13:26 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +      return ExprMutator::VisitBinding_(binding);
Construct a separate visitor(not mutator) TIRFuncFusor to collect the information needed for fusion

2022-04-03 12:06 UTC, jinhongyii commented
@tqchen @Hzfengsy @MasterJH5574  I've refactored FuseTIR and you can have another round of review

2022-04-04 12:29 UTC, tqchen commented on src/relax/transform/fuse_tir.cc
> +  tir::PrimFunc fused_tir;
STYLE: this is something that we must always follow in instinct and avoid code review effort. Private member should all have an trailing underscore.

2022-04-04 14:11 UTC, merged